name: Build and Deploy Android to Play Store

on:
  push:
    branches: [ main ]
    paths:
      - 'client/**'
      - 'server/**'
      - 'shared/**'
      - 'android/**'
      - 'package.json'
      - 'capacitor.config.ts'
  workflow_dispatch:

env:
  NODE_VERSION: '20'
  JAVA_VERSION: '17'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ env.JAVA_VERSION }}
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Install dependencies
      run: npm install
      
    - name: Build web app (client only)
      run: npx vite build --config client/vite.config.ts
      env:
        NODE_ENV: production
      
    - name: Sync Capacitor Android
      run: npx cap sync android
      
    - name: Make Gradle executable
      run: chmod +x ./android/gradlew
      
    - name: Build Android Debug AAB (for initial testing)
      run: |
        cd android
        ./gradlew bundleDebug
      continue-on-error: false
      
    # Note: Uncomment below after you have signing key set up
    # - name: Build Android Release AAB
    #   run: |
    #     cd android
    #     ./gradlew bundleRelease
    #   continue-on-error: false
    #   
    # - name: Sign Android Release
    #   id: sign
    #   uses: r0adkll/sign-android-release@v1
    #   with:
    #     releaseDirectory: android/app/build/outputs/bundle/release
    #     signingKeyBase64: ${{ secrets.SIGNING_KEY }}
    #     alias: ${{ secrets.ALIAS }}
    #     keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
    #     keyPassword: ${{ secrets.KEY_PASSWORD }}
        
    # Note: Uncomment below after setting up Google Play service account
    # - name: Upload to Play Store (Internal Track)
    #   uses: r0adkll/upload-google-play@v1
    #   with:
    #     serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
    #     packageName: com.deleboston.healthwise
    #     releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
    #     track: internal
    #     status: completed
    #     inAppUpdatePriority: 2
        
    - name: Upload AAB as artifact
      uses: actions/upload-artifact@v4
      with:
        name: healthwise-app-bundle-debug
        path: android/app/build/outputs/bundle/debug/app-debug.aab
        retention-days: 30
